name: Build and Publish Docker Image

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-and-publish-docker-image.yml"

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/discord-chat-exporter-incremental:latest
          docker push ghcr.io/${{ github.actor }}/discord-chat-exporter-incremental:latest
